%YAML:1.0

# --------------------------------------------------------------------------------------------
# Camera Parameters (OAK-D RGB-D 320x240)
# --------------------------------------------------------------------------------------------
File.version: "1.0"
Camera.type: "PinHole"

# --- OAK-D Intrinsics ---
Camera.width: 320
Camera.height: 240
Camera.fps: 30
Camera.RGB: 1

# Intrinsics from your bag (fx, fy, cx, cy)
Camera1.fx: 277.0
Camera1.fy: 277.0
Camera1.cx: 160.0
Camera1.cy: 120.0

# Distortion (Zero)
Camera1.k1: 0.0
Camera1.k2: 0.0
Camera1.p1: 0.0
Camera1.p2: 0.0

# --- Depth Sensor Specifics ---
# 1.0 because 32FC1 is in Meters.
RGBD.DepthMapFactor: 1.0

# Thresholds (Required for RGB-D)
RGBD.ThDepth: 40.0
Stereo.ThDepth: 40.0
Stereo.b: 0.075

# --------------------------------------------------------------------------------------------
# ORB Parameters
# --------------------------------------------------------------------------------------------
ORBextractor.nFeatures: 2000
ORBextractor.scaleFactor: 1.2
ORBextractor.nLevels: 8
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

# --------------------------------------------------------------------------------------------
# Viewer Parameters
# --------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500.0
