%YAML:1.0

# --------------------------------------------------------------------------------------------
# Camera Parameters (OAK-D Mono 320x240)
# --------------------------------------------------------------------------------------------
File.version: "1.0"
Camera.type: "PinHole"

# --- Image Config ---
Camera.width: 320
Camera.height: 240
Camera.fps: 30
Camera.RGB: 1

# --- Intrinsics (From your Bag) ---
Camera1.fx: 277.0
Camera1.fy: 277.0
Camera1.cx: 160.0
Camera1.cy: 120.0

# --- Distortion (Rectified/Zero) ---
Camera1.k1: 0.0
Camera1.k2: 0.0
Camera1.p1: 0.0
Camera1.p2: 0.0

# --------------------------------------------------------------------------------------------
# ORB Feature Parameters
# --------------------------------------------------------------------------------------------
# Higher features = Denser map, but slower. 2000 is a good balance for OAK-D.
ORBextractor.nFeatures: 4000
ORBextractor.scaleFactor: 1.2
ORBextractor.nLevels: 5
ORBextractor.iniThFAST: 10
ORBextractor.minThFAST: 5

# --------------------------------------------------------------------------------------------
# Viewer Parameters
# --------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500.0
